[[session]]
name = "dotfiles"
path = "~/.local/share/chezmoi/"
# startup_command = "nvim -c 'lua require(\"lazyvim.util\").pick(\"files\")()'"
windows = ["chezmoi.toml", "config"]

[[window]]
name = "chezmoi.toml"
path = "~/.config/chezmoi/"
startup_command = "nvim chezmoi.toml"

[[window]]
name = "config"
path = "~/.config/"
startup_command = "yazi"
